### ISSUE TITLE
Modal not functioning when using Inertia v2.x [Beta]

### ISSUE THREAD

**Issue by renekragelundpedersen** [inertiaui/modal#46]
I know that the Inertia v2 is in Beta, and just wanted to drop a comment here, since i could not find any other issues posted on this.

Using Inertia (currently 2.0.0-beta.2), the Inertaui modals are not working anymore. Not getting any direct errors that i can share, the modals is just never showing. Going back to Inertia 1.2.0, everything is working as expected.

I know that it is still en beta, but just wanted to put this out there, maybe someone got more information on it than i can currently gather.

Thank you for this awesome framework.

**Comment by pascalbaljet** [comment]
Thanks for reporting! Also, are there no errors in the console?

**Comment by renekragelundpedersen** [comment]
No console errors :smiley: 
The ModalLink makes the request to the route and all, the modal just never seems to get inserted to the DOM it seems?
I can't find any modal element in the dom after the request is finished, like i usually can when using 1.x of inertia.

So i'm sorry, but i can't really share any logs on anything :smile:

**Comment by velipx** [comment]
It's the same for me, is there a solution to use inertiaui/modal with Inertia 2.0 beta?

**Comment by pascalbaljet** [comment]
Fixed in v0.12.1 👌 For future reference, I reproduced it like this:

#### Setup new Laravel project with Breeze (Inertia.js + Vue.js), upgrade Inertia.js to v2, and install Inertia Modal:
```bash
laravel new modal-inertiav2-test --stack=vue --breeze --phpunit -n
cd modal-inertiav2-test
composer require inertiajs/inertia-laravel:2.x-dev
npm install @inertiajs/vue3@next
composer require inertiaui/modal
npm install vendor/inertiaui/modal/vue
# Then follow the Inertia.js + Tailwind instructions from https://inertiaui.com/inertia-modal/docs/installation
```

#### Add a modal route in `routes/web.php`

```php
Route::get('/modal', fn () => Inertia::modal('Modal')->baseUrl('/'));
```

#### Create the Modal component in `resources/js/Pages/Modal.vue`

```vue
<script setup>
import { Modal } from '@inertiaui/modal-vue'
</script>

<template>
    <Modal>
        <h1>Test Modal</h1>
    </Modal>
</template>
```

#### Add a ModalLink in `resources/js/Pages/Welcome.vue`

```vue
<script setup>
// Add import
import { ModalLink } from '@inertiaui/modal-vue'
</script>

<template>
    <!-- Replace background svg image with ModaLink: -->
    <ModalLink navigate href="/modal">Open Modal</ModalLink>
</template>
```

#### Build the assets

```bash
npm run build
```

**Comment by renekragelundpedersen** [comment]
Hi again @pascalbaljet.
thank you for the update!

I tried upgrading to 0.12.1 (and also 0.13.1) - it still does not work for me, with the same result.
No errors in the console, just like before.

I tried changing my `<ModaLink>` to have the "navigate" attribute along with it, which actually produces errors we might be able to use:

`Cannot read properties of undefined (reading 'shouldRender')
    at Proxy.<anonymous> (@inertiaui_modal-vue.js?v=5bafe9ab:534:15)`

![image](https://github.com/user-attachments/assets/9423a3f2-33ba-4cbd-9617-0319f97e3770)

I tried with a blank installation, following your reference for reproducing aswell.
Using the route: 
`Route::get('/modal', fn () => Inertia::modal('Modal')->baseUrl('/'));`

The request is pending and timing out.

Changing the route to:
`Route::get('/modal', fn () => Inertia::render('Modal'));`

The error form me other project is being reproduced:
`Cannot read properties of undefined (reading 'shouldRender')
    at Proxy.<anonymous> (@inertiaui_modal-vue.js?v=5bafe9ab:534:15)`

**Comment by takielias** [comment]
@pascalbaljet Still facing the same issue no Modal popup.

**Comment by renekragelundpedersen** [comment]
Hi again, @pascalbaljet .
Just got the time to test this out again, and now testing with our version 0.16 (i also tested v0.14).

I still encounter the same issue as before, with exactly the same happening. @takielias or @velipx, have you guys got it to work, just to make sure it is not just at my end?

![image](https://github.com/user-attachments/assets/a997c22a-787e-4e29-b886-81a3e9863486)
![image](https://github.com/user-attachments/assets/b8036b9b-7f39-4277-83e8-e12985b29bc5)

**Comment by renekragelundpedersen** [comment]
Just want to end this one, by pointing out it now works as expected.
Do not forget to update the app.js render function (if you use Vue), to the new standard as described in the InertiaUI documentation.

**Comment by pascalbaljet** [comment]
> Just want to end this one, by pointing out it now works as expected. Do not forget to update the app.js render function (if you use Vue), to the new standard as described in the InertiaUI documentation.

Ah, great! Thanks for reporting back :)
